/// @desc initialize
spd = 80;
hspd = 0;
vspd = 0;
dir = 0;
stepCounter = 0;
stepMax = 25;
maxHealth = 100;
health = maxHealth;
image_xscale = 0.5;
image_yscale = image_xscale;
knockbackX = 0;
knockbackY = 0;
invincibilityFrames = 0;
outlineSprite = spr_playerOutline;
pointerRotation = 0;