/// @desc initialize
spd = 1;
hspd = 0;
vspd = 0;
len = 0;
dir = 0;
bullets = ds_list_create();
stepCounter = 0;
stepMax = 25;
maxHealth = 100;
health = maxHealth;
sprite_index = spr_player;
image_xscale = 3/200;
image_yscale = 3/200;