/// @desc initialize
spd = 1;
hspd = 0;
vspd = 0;
dir = 0;
stepCounter = 0;
stepMax = 25;
maxHealth = 100;
health = maxHealth;
sprite_index = spr_player;
image_xscale = 3/200;
image_yscale = 3/200;
knockbackX = 0;
knockbackY = 0;
invincibilityFrames = 0;